services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=ArinA_ArinA1
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - plugins.security.disabled=true   # ОТЛАДКА ТОЛЬКО
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSk https://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 12
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  app:
    build: .
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
    # если приложение запускается снаружи (на хосте), вместо opensearch укажите localhost

volumes:
  opensearch-data: